// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personnel_Management.Models.Models;

#nullable disable

namespace Personnel_Management.Data.Migrations
{
    [DbContext(typeof(QuanLyNhanSuContext))]
    partial class QuanLyNhanSuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personnel_Management.Models.Models.DiemDanh", b =>
                {
                    b.Property<int>("DiemDanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiemDanhId"));

                    b.Property<string>("LyDoVangMat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDiemDanh")
                        .HasColumnType("date");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianVao")
                        .HasColumnType("datetime");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("DiemDanhId")
                        .HasName("PK__DiemDanh__972C4F6310BFB9DF");

                    b.HasIndex("NhanVienId");

                    b.ToTable("DiemDanh", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.LichNghi", b =>
                {
                    b.Property<int>("LichNghiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichNghiId"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.HasKey("LichNghiId");

                    b.ToTable("LichNghis");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.Luong", b =>
                {
                    b.Property<int>("LuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuongId"));

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("LuongId")
                        .HasName("PK__Luong__10D2B7F3923B0186");

                    b.HasIndex("NhanVienId");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("matkhau");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienId")
                        .HasName("PK__NhanVien__E27FD78A073F81C3");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D105341ECBCE78")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.PhongBan", b =>
                {
                    b.Property<int>("PhongBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongBanId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PhongBanId")
                        .HasName("PK__PhongBan__F417DBA86354CE71");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1AB4D817DD");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__8A2B61602CDE48DE")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.ThuongPhat", b =>
                {
                    b.Property<int>("ThuongPhatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuongPhatId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ThuongPhatId")
                        .HasName("PK__ThuongPh__B0C88F4C2E3A96C0");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ThuongPhat", (string)null);
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.DiemDanh", b =>
                {
                    b.HasOne("Personnel_Management.Models.Models.NhanVien", "NhanVien")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("NhanVienId")
                        .IsRequired()
                        .HasConstraintName("FK__DiemDanh__NhanVi__45F365D3");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.Luong", b =>
                {
                    b.HasOne("Personnel_Management.Models.Models.NhanVien", "NhanVien")
                        .WithMany("Luongs")
                        .HasForeignKey("NhanVienId")
                        .IsRequired()
                        .HasConstraintName("FK__Luong__NhanVienI__4222D4EF");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.NhanVien", b =>
                {
                    b.HasOne("Personnel_Management.Models.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__PhongB__3F466844");

                    b.HasOne("Personnel_Management.Models.Models.Role", "Role")
                        .WithMany("NhanViens")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__RoleId__3E52440B");

                    b.Navigation("PhongBan");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.ThuongPhat", b =>
                {
                    b.HasOne("Personnel_Management.Models.Models.NhanVien", "NhanVien")
                        .WithMany("ThuongPhats")
                        .HasForeignKey("NhanVienId")
                        .IsRequired()
                        .HasConstraintName("FK__ThuongPha__NhanV__48CFD27E");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.NhanVien", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("Luongs");

                    b.Navigation("ThuongPhats");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Personnel_Management.Models.Models.Role", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
