// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Management.Models.Models;

public partial class QuanLyNhanSuContext : DbContext
{
    public QuanLyNhanSuContext(DbContextOptions<QuanLyNhanSuContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DiemDanh> DiemDanhs { get; set; }

    public virtual DbSet<Luong> Luongs { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhongBan> PhongBans { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ThuongPhat> ThuongPhats { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DiemDanh>(entity =>
        {
            entity.HasKey(e => e.DiemDanhId).HasName("PK__DiemDanh__972C4F6310BFB9DF");

            entity.ToTable("DiemDanh");

            entity.Property(e => e.LyDoVangMat).HasMaxLength(255);
            entity.Property(e => e.NgayDiemDanh).HasColumnType("date");
            entity.Property(e => e.ThoiGianRa).HasColumnType("datetime");
            entity.Property(e => e.ThoiGianVao).HasColumnType("datetime");

            entity.HasOne(d => d.NhanVien).WithMany(p => p.DiemDanhs)
                .HasForeignKey(d => d.NhanVienId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DiemDanh__NhanVi__45F365D3");
        });

        modelBuilder.Entity<Luong>(entity =>
        {
            entity.HasKey(e => e.LuongId).HasName("PK__Luong__10D2B7F3923B0186");

            entity.ToTable("Luong");

            entity.Property(e => e.LuongCoBan).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NgayCapNhat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.PhuCap).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.NhanVien).WithMany(p => p.Luongs)
                .HasForeignKey(d => d.NhanVienId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Luong__NhanVienI__4222D4EF");
        });

        modelBuilder.Entity<NhanVien>(entity =>
        {
            entity.HasKey(e => e.NhanVienId).HasName("PK__NhanVien__E27FD78A073F81C3");

            entity.ToTable("NhanVien");

            entity.HasIndex(e => e.Email, "UQ__NhanVien__A9D105341ECBCE78").IsUnique();

            entity.Property(e => e.Email).HasMaxLength(255);
			entity.Property(e => e.Avatar).HasMaxLength(255);
			entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Matkhau)
                .HasMaxLength(50)
                .HasColumnName("matkhau");
            entity.Property(e => e.NgaySinh).HasColumnType("date");
            entity.Property(e => e.SoDienThoai).HasMaxLength(20);

            entity.HasOne(d => d.PhongBan).WithMany(p => p.NhanViens)
                .HasForeignKey(d => d.PhongBanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NhanVien__PhongB__3F466844");

            entity.HasOne(d => d.Role).WithMany(p => p.NhanViens)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NhanVien__RoleId__3E52440B");
        });

        modelBuilder.Entity<PhongBan>(entity =>
        {
            entity.HasKey(e => e.PhongBanId).HasName("PK__PhongBan__F417DBA86354CE71");

            entity.ToTable("PhongBan");

            entity.Property(e => e.TenPhongBan)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1AB4D817DD");

            entity.ToTable("Role");

            entity.HasIndex(e => e.RoleName, "UQ__Role__8A2B61602CDE48DE").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<ThuongPhat>(entity =>
        {
            entity.HasKey(e => e.ThuongPhatId).HasName("PK__ThuongPh__B0C88F4C2E3A96C0");

            entity.ToTable("ThuongPhat");

            entity.Property(e => e.Loai)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.SoTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.NhanVien).WithMany(p => p.ThuongPhats)
                .HasForeignKey(d => d.NhanVienId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ThuongPha__NhanV__48CFD27E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}