// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personnel_Management.Models.Models;

public partial class DiemDanh
{
    public int DiemDanhId { get; set; }

    public int NhanVienId { get; set; }

    public DateTime NgayDiemDanh { get; set; }

    public DateTime? ThoiGianVao { get; set; }

    public DateTime? ThoiGianRa { get; set; }

    public bool? TrangThai { get; set; }

    public string LyDoVangMat { get; set; }

    public virtual NhanVien NhanVien { get; set; }
}