// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personnel_Management.Models.Models;

public partial class NhanVien
{
    public int NhanVienId { get; set; }

    public string HoTen { get; set; }

    public DateTime? NgaySinh { get; set; }

    public string DiaChi { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public int RoleId { get; set; }

    public int PhongBanId { get; set; }

    public string Matkhau { get; set; }

    public virtual ICollection<DiemDanh> DiemDanhs { get; set; } = new List<DiemDanh>();

    public virtual ICollection<Luong> Luongs { get; set; } = new List<Luong>();

    public virtual PhongBan PhongBan { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<ThuongPhat> ThuongPhats { get; set; } = new List<ThuongPhat>();
}