// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personnel_Management.Models.Models;

public partial class PhongBan
{
    public int PhongBanId { get; set; }

    public string TenPhongBan { get; set; }

    public string MoTa { get; set; }

    public virtual ICollection<NhanVien> NhanViens { get; set; } = new List<NhanVien>();
}