// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personnel_Management.Models.Models;

public partial class ThuongPhat
{
    public int ThuongPhatId { get; set; }

    public int NhanVienId { get; set; }

    public DateTime Ngay { get; set; }

    public decimal SoTien { get; set; }

    public string Loai { get; set; }

    public string GhiChu { get; set; }

    public virtual NhanVien NhanVien { get; set; }
}